context:
  version: "35.1"
  major: 6

package:
  name: protobuf-bazel-rules
  version: ${{ version }}

source:
  url: https://github.com/protocolbuffers/protobuf/releases/download/v${{ version }}/protobuf-${{ version }}.tar.gz
  sha256: f0b6838e7522a8da96126d487068c959bc624926368f3024ac8fd03abd0a1ac4

build:
  number: 0
  noarch: generic

requirements:
  run_constraints:
    - protobuf ${{ major }}.${{ version }}.*
    - libprotobuf ${{ major }}.${{ version }}.*

tests:
  - package_contents:
      files:
        - share/bazel/protobuf/bazel/cc_proto_library.bzl
        - share/bazel/upb/bazel/upb_c_proto_library.bzl

about:
  homepage: https://developers.google.com/protocol-buffers/
  repository: https://github.com/protocolbuffers/protobuf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bazel rules for protobuf

extra:
  recipe-maintainers:
    - conda-forge/libprotobuf
